export enum ApprovalType {
  ARCHITECTURE_APPROVAL = "ARCHITECTURE_APPROVAL",
  IMPLEMENTATION_APPROVAL = "IMPLEMENTATION_APPROVAL",
  MERGE_APPROVAL = "MERGE_APPROVAL",
  PRODUCTION_APPROVAL = "PRODUCTION_APPROVAL"
}

export enum ApprovalStatus {
  PENDING = "PENDING",
  APPROVED = "APPROVED",
  REJECTED = "REJECTED",
  EXPIRED = "EXPIRED"
}
